pipeline{
  agent none
  stages{

    stage('Back-end'){
      agent{
        docker { image 'maven:3.8.1-adoptopenjdk-11' }
      }
      steps{
        sh 'mvn --version'
      }
    }
    stage('Front-end'){
      agent{
        docker { image 'node:16-alpine' }
      }
      steps{
        sh 'node --version'
      }
    }
    stage('Database'){
      agent{
        docker { image 'mysql:latest' }
      }
      steps {
        echo "=== Checking MySQL container ==="
        sh '''
            mysql --version
            echo "Simulating DB setup..."
            sleep 3
            echo "MySQL container is working fine!"
        '''
      }
    }  
  }
}
